### ISSUE TITLE
构造请求参数的时候没有对请求PublicKey进URLEncode

### ISSUE THREAD

**Issue by sunshinespringsnow** [ucloud/ucloud-sdk-java#1]
<img width="822" alt="2018-11-09 5 24 28" src="https://user-images.githubusercontent.com/20733755/48254266-867c4400-e444-11e8-924b-e30eeefa5177.png">
签名文档中说明如果publicKey包含特殊字符需要对参数进行URLEncode，但是代码在处理时特殊排除了
publicKey
<img width="983" alt="2018-11-09 5 27 57" src="https://user-images.githubusercontent.com/20733755/48254378-da872880-e444-11e8-9b00-3a0371fb7b01.png">
使用sdk访问接口publicKey存在特殊字符，会出现 user not existed 的问题

**Comment by peggypig** [comment]
你好，这个问题已在0.6.1-release版本中解决。
