### ISSUE TITLE
ulb返回信息不全

### ISSUE THREAD

**Issue by hellorocky** [ucloud/ucloud-sdk-java#3]
缺少VPC ID, 麻烦更新下吧, 我们业务上有需要.

**Comment by JoshuaYin** [comment]
@hellorocky ULB中的哪个API ？

**Comment by hellorocky** [comment]
> @hellorocky ULB中的哪个API ？

describeULB

**Comment by hellorocky** [comment]
另外我们业务上也用到了MySQL和MongoDB, 也需要同步到我们本地, 这个SDK也麻烦尽快支持吧

**Comment by peggypig** [comment]
@hellorocky 相关接口返回与实际有出入的问题，在0.6.3-release中已经修复
